CREATE TABLE hive_activity
(
  id SERIAL PRIMARY KEY,
  action TEXT,
  notes TEXT,
  date_added TIMESTAMPTZ NOT NULL DEFAULT now(),
  hive_id INTEGER REFERENCES hives(id) ON DELETE CASCADE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);
